@baseURL = http://localhost:8000/api/
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjMsImV4cCI6MTYyNDIwNTEzM30.7-MbWMBTsZ83Utd5SYaK3ltvpSQnWaTdjCGJzrXxMTY

GET {{baseURL}}stores/

###

POST {{baseURL}}stores/
Content-Type: application/json

{
  "name": "Test place",
  "imageShop": "image.shop",
  "imageProduct": "image.product",
  "address": "123 asd rd",
  "description": "Tester"
}

###

GET {{baseURL}}stores/1/

###

PUT {{baseURL}}stores/4/
Content-Type: application/json

{
  "name": "NEW NAME",
  "imageShop": "image.shop",
  "imageProduct": "image.product",
  "address": "123 asd rd",
  "description": "NEW DESCRIPTION"
}

###

DELETE {{baseURL}}stores/5/
Content-Type: application/json

###

POST {{baseURL}}auth/register/
Content-Type: application/json

{
  "username": "dee2",
  "email": "dee@email2.com",
  "password": "password",
  "passwordConfirmation": "password",
  "profileImage": "image.jpg"
}

###

POST {{baseURL}}auth/login/
Content-Type: application/json

{
  "email": "dee@email2.com",
  "password": "password"
}

###

POST http://localhost:8000/api/stores/1/favourite/
Authorization: Bearer {{token}}

###

GET {{baseURL}}auth/profile/3/