@baseURL = http://localhost:8000/api/

GET {{baseURL}}stores/

###

POST {{baseURL}}stores/
Content-Type: application/json

{
  "name": "Test place",
  "imageShop": "image.shop",
  "imageProduct": "image.product",
  "address": "123 asd rd",
  "description": "Tester"
}

###

GET {{baseURL}}stores/4/

###

PUT {{baseURL}}stores/4/
Content-Type: application/json

{
  "name": "NEW NAME",
  "imageShop": "image.shop",
  "imageProduct": "image.product",
  "address": "123 asd rd",
  "description": "NEW DESCRIPTION"
}

###

DELETE {{baseURL}}stores/5/
Content-Type: application/json

###

POST {{baseURL}}auth/register/
Content-Type: application/json

{
  "username": "dee1",
  "email": "dee@email1.com",
  "password": "password",
  "passwordConfirmation": "password",
  "profileImage": "image.jpg"
}

###

POST {{baseURL}}auth/login/
Content-Type: application/json

{
  "email": "dee@email1.com",
  "password": "password"
}

###

GET {{baseURL}}auth/profile/1/