# Generated by Django 3.2.4 on 2021-06-13 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20210612_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='favourites',
        ),
    ]
